### ISSUE TITLE
questions about "how to find_package"

### ISSUE THREAD

**Issue by HuJiaming11** [bit-ivrc/cmake_tutorial#1]
After instruction "cmake ..",package_FOUND is ture, but package_LIBRARY_DIR is void,how to deal with this problem?

**Comment by ytiang** [comment]
which package? some package config files do not set variable "package_LIBRARY_DIR". You can see which variables are set in <package>Config.cmake file.
1. when the variables are empty, please check whether  the prefix is right, in variable <xxx_LIBRARY_DIR>.
1. The most important variables are "package_INCLUDE_DIRS" and "packge_LIBRARIES". They may be empty. Some packages are headers-only libraries which just contain the header files, like eigen, variable EIGEN3_LIBRARIES is empty. Some package are called IMPORT target, the config file only set variable "xxx_LIBRARIES" and variable "xxx_INCLUDE_DIRS" is empty.
