### ISSUE TITLE
CMake Error at CMakeLists.txt : xx (find_package)

### ISSUE THREAD

**Issue by GodYaoyao** [bit-ivrc/cmake_tutorial#3]
By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by ytiang** [comment]
which package? 'catkin' is required from ROS package, you must complie an ros package in ros workspace. If you don't resolve this problem, please provide more detailed information by using this [issue template](https://github.com/bit-ivrc/issue_and_pr_templates/blob/master/.github/ISSUE_TEMPLATE.md)
